/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.JFrame;

/**
 *
 * @author LuisFuentes
 */
public class AccionView extends javax.swing.JFrame {

    private String articulo;
    private javax.swing.JFrame inventarioForm;

    public JFrame getInventarioForm() {
        return inventarioForm;
    }

    public void setInventarioForm(JFrame inventarioForm) {
        this.inventarioForm = inventarioForm;
    }

    public String getArticulo() {
        return articulo;
    }

    public void setArticulo(String articulo) {
        this.articulo = articulo;
    }
    /**
     * Creates new form AccionView
     */
    public AccionView() {
        initComponents();
        Accion_panel.setSize(230, 300);
        this.setSize(230, 300);
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        articulo_label.setText(articulo);
        costo_total_txt.setText(articulo);
        System.out.println("Articulo: "+this.articulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Accion_panel = new javax.swing.JPanel();
        comprar_rButton = new javax.swing.JRadioButton();
        vender_rButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        anio_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cantidad_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        costo_unitario_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        costo_total_txt = new javax.swing.JTextField();
        aceptar_button = new javax.swing.JButton();
        cancelar_button = new javax.swing.JButton();
        dia_txt = new javax.swing.JTextField();
        mes_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        articulo_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(comprar_rButton);
        comprar_rButton.setSelected(true);
        comprar_rButton.setText("Comprar");
        comprar_rButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprar_rButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(vender_rButton);
        vender_rButton.setText("Vender");
        vender_rButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vender_rButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Acción:");

        jLabel2.setText("Fecha:");

        anio_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anio_txtKeyTyped(evt);
            }
        });

        jLabel3.setText("Cantidad:");

        jLabel4.setText("Artículo:");

        cantidad_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidad_txtKeyTyped(evt);
            }
        });

        jLabel5.setText("Costo unitario:");

        costo_unitario_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costo_unitario_txtKeyTyped(evt);
            }
        });

        jLabel6.setText("Costo total:");

        costo_total_txt.setEditable(false);

        aceptar_button.setText("Aceptar");

        cancelar_button.setText("Cancelar");

        dia_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dia_txtKeyTyped(evt);
            }
        });

        mes_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mes_txtKeyTyped(evt);
            }
        });

        jLabel7.setText("Día");

        jLabel8.setText("Mes");

        jLabel9.setText("Año");

        articulo_label.setText("articulo");

        javax.swing.GroupLayout Accion_panelLayout = new javax.swing.GroupLayout(Accion_panel);
        Accion_panel.setLayout(Accion_panelLayout);
        Accion_panelLayout.setHorizontalGroup(
            Accion_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Accion_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Accion_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Accion_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Accion_panelLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(24, 24, 24)
                            .addComponent(costo_total_txt))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Accion_panelLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(costo_unitario_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Accion_panelLayout.createSequentialGroup()
                        .addComponent(aceptar_button)
                        .addGap(18, 18, 18)
                        .addComponent(cancelar_button))
                    .addGroup(Accion_panelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidad_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Accion_panelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(articulo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Accion_panelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comprar_rButton)
                        .addGap(10, 10, 10)
                        .addComponent(vender_rButton))
                    .addGroup(Accion_panelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Accion_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dia_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Accion_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Accion_panelLayout.createSequentialGroup()
                                .addComponent(mes_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anio_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Accion_panelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        Accion_panelLayout.setVerticalGroup(
            Accion_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Accion_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Accion_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Accion_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dia_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mes_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anio_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(Accion_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(vender_rButton)
                    .addComponent(comprar_rButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Accion_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(articulo_label))
                .addGap(16, 16, 16)
                .addGroup(Accion_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cantidad_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Accion_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(costo_unitario_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Accion_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(costo_total_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Accion_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar_button)
                    .addComponent(cancelar_button))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Accion_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Accion_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 200, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantidad_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad_txtKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0') | (caracter > '9')) & (caracter != '\b')) {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_cantidad_txtKeyTyped

    private void costo_unitario_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costo_unitario_txtKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0') | (caracter > '9')) & (caracter != '\b') & (caracter != '.')) {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_costo_unitario_txtKeyTyped

    private void vender_rButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vender_rButtonActionPerformed
        costo_unitario_txt.setEditable(false);
    }//GEN-LAST:event_vender_rButtonActionPerformed

    private void comprar_rButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprar_rButtonActionPerformed
        costo_unitario_txt.setEditable(true);
    }//GEN-LAST:event_comprar_rButtonActionPerformed

    private void dia_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dia_txtKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0') | (caracter > '9')) & (caracter != '\b')) {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_dia_txtKeyTyped

    private void mes_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mes_txtKeyTyped
        char caracter = evt.getKeyChar();
        String mes = mes_txt.getText().trim();

        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0') | (caracter > '9')) & (caracter != '\b')) {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_mes_txtKeyTyped

    private void anio_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anio_txtKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0') | (caracter > '9')) & (caracter != '\b')) {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_anio_txtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccionView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Accion_panel;
    private javax.swing.JButton aceptar_button;
    private javax.swing.JTextField anio_txt;
    public javax.swing.JLabel articulo_label;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelar_button;
    private javax.swing.JTextField cantidad_txt;
    private javax.swing.JRadioButton comprar_rButton;
    private javax.swing.JTextField costo_total_txt;
    private javax.swing.JTextField costo_unitario_txt;
    private javax.swing.JTextField dia_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mes_txt;
    private javax.swing.JRadioButton vender_rButton;
    // End of variables declaration//GEN-END:variables
}
