/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.sql.*;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import db_connection.DBconnection;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Luis Fuentes <luisfuau10@gmail.com>
 */
public class InventarioView extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    public DBconnection conexion;
    public static Connection con;
    public static PreparedStatement ps;
    public static ResultSet rs;    

    /**
     * Creates new form InventarioView
     */
    public InventarioView() {
        initComponents();
        llenarComboBox();
        Inventario_panel.setSize(1150, 400);
        this.setSize(1150, 400);
        this.setTitle("Tarjeta Kardex");
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        jTable_inventario = new JTable(model);
        jScrollPane.setViewportView(jTable_inventario);

        model.addColumn("FECHA");
        model.addColumn("DETALLE");

        model.addColumn("Q");
        model.addColumn("COSTO UNITARIO");
        model.addColumn("COSTO TOTAL");

        model.addColumn("Q");
        model.addColumn("COSTO UNITARIO");
        model.addColumn("COSTO TOTAL");

        model.addColumn("Q");
        model.addColumn("COSTO UNITARIO");
        model.addColumn("COSTO TOTAL");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inventario_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        producto_cbox = new javax.swing.JComboBox<>();
        jScrollPane = new javax.swing.JScrollPane();
        jTable_inventario = new javax.swing.JTable();
        newProduct_button = new javax.swing.JButton();
        mostrar_button = new javax.swing.JButton();
        acciones_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inventario_panel.setPreferredSize(new java.awt.Dimension(1030, 530));

        jLabel2.setFont(new java.awt.Font("Muli", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TARJETA KARDEX");

        jLabel1.setFont(new java.awt.Font("Muli", 0, 14)); // NOI18N
        jLabel1.setText("Artículo:");

        producto_cbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        producto_cbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                producto_cboxMouseClicked(evt);
            }
        });

        jScrollPane.setPreferredSize(new java.awt.Dimension(1030, 530));

        jTable_inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Título 5", "Título 6", "Título 7", "Título 8", "Título 9", "Título 10", "Título 11"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_inventario.setPreferredSize(new java.awt.Dimension(1030, 530));
        jScrollPane.setViewportView(jTable_inventario);

        newProduct_button.setText("Nuevo artículo");
        newProduct_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProduct_buttonActionPerformed(evt);
            }
        });

        mostrar_button.setText("Mostrar");
        mostrar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrar_buttonActionPerformed(evt);
            }
        });

        acciones_button.setText("Acciones");
        acciones_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acciones_buttonActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ENTRADAS");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SALIDAS");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SALDO");

        javax.swing.GroupLayout Inventario_panelLayout = new javax.swing.GroupLayout(Inventario_panel);
        Inventario_panel.setLayout(Inventario_panelLayout);
        Inventario_panelLayout.setHorizontalGroup(
            Inventario_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1150, Short.MAX_VALUE)
            .addGroup(Inventario_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(producto_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrar_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(acciones_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newProduct_button)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Inventario_panelLayout.createSequentialGroup()
                .addGroup(Inventario_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Inventario_panelLayout.createSequentialGroup()
                        .addGap(492, 492, 492)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Inventario_panelLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Inventario_panelLayout.setVerticalGroup(
            Inventario_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventario_panelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Inventario_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Inventario_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(producto_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrar_button)
                    .addComponent(newProduct_button)
                    .addComponent(acciones_button))
                .addGap(22, 22, 22))
        );

        getContentPane().add(Inventario_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newProduct_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProduct_buttonActionPerformed
        nuevoProductoView();
    }//GEN-LAST:event_newProduct_buttonActionPerformed

    private void producto_cboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_producto_cboxMouseClicked
        llenarComboBox();
    }//GEN-LAST:event_producto_cboxMouseClicked

    private void mostrar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrar_buttonActionPerformed
        llenarTabla();
    }//GEN-LAST:event_mostrar_buttonActionPerformed

    private void acciones_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acciones_buttonActionPerformed
        accionesView();
    }//GEN-LAST:event_acciones_buttonActionPerformed

    void accionesView(){
       AccionView accionView = new AccionView();
       //accionView.setInventarioForm(this);
       accionView.articulo_label.setText(producto_cbox.getSelectedItem().toString().trim());
       accionView.setVisible(true);
    }
    
    void nuevoProductoView() {
        ProductoView productoView = new ProductoView();
        productoView.setVisible(true);
    }

    void llenarTabla() {
        try {
            limpiarTabla();
            String query = ("SELECT \n"
                    + "    inventario.fecha,\n"
                    + "    detalle.nombre_detalle,\n"
                    + "    inventario.cantidad_entrada,\n"
                    + "    inventario.entrada_unitario,\n"
                    + "    inventario.entrada_total,\n"
                    + "    inventario.cantidad_salida,\n"
                    + "    inventario.salida_unitaria,\n"
                    + "    inventario.salida_total,\n"
                    + "    inventario.cantidad_pro,\n"
                    + "    inventario.unitario_pro,\n"
                    + "    inventario.total_pro\n"
                    + "FROM kardex inventario\n"
                    + "INNER JOIN detalle\n"
                    + "	ON detalle.id_detalle = inventario.id_detalle\n"
                    + "INNER JOIN producto\n"
                    + "	ON producto.id_producto = inventario.id_producto\n"
                    + "WHERE producto.nombre_producto = ? ");

            conexion = new DBconnection("localhost", "3307", "inventario_db", "root", "Mysql@fuentech2018");
            con = conexion.getConnection();
            ps = con.prepareStatement(query);
            ps.setString(1, producto_cbox.getSelectedItem().toString());

            rs = ps.executeQuery();

            while (rs.next()) {
                Object[] fila = new Object[11];

                for (int i = 0; i < 11; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            con.close();
            //}

        } catch (SQLException ex) {
            Logger.getLogger(InventarioView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void limpiarTabla() {
        try {
            int numFilas = jTable_inventario.getRowCount();
            if (numFilas > 0) {
                for (int i = 0; i < numFilas; i++) {
                    model.removeRow(0);
                }
            }
        } catch (Exception e) {

        }
    }

    void llenarComboBox() {
        producto_cbox.removeAllItems();
        producto_cbox.addItem("Seleccionar");
        try {
            String query = "SELECT nombre_producto FROM producto";
            conexion = new DBconnection("localhost", "3307", "inventario_db", "root", "Mysql@fuentech2018");
            con = conexion.getConnection();
            ps = con.prepareStatement(query);
            rs = ps.executeQuery();

            while (rs.next()) {
                producto_cbox.addItem(rs.getString("nombre_producto"));
            }
            con.close();

        } catch (SQLException ex) {
            Logger.getLogger(InventarioView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void limpiarComboBox() {
        int cantidad = producto_cbox.getItemCount();

        for (int i = 0; i < cantidad; i++) {
            producto_cbox.removeItemAt(0);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Inventario_panel;
    private javax.swing.JButton acciones_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable_inventario;
    private javax.swing.JButton mostrar_button;
    private javax.swing.JButton newProduct_button;
    private javax.swing.JComboBox<String> producto_cbox;
    // End of variables declaration//GEN-END:variables
}
